// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static java.util.List<myfirstmodule.proxies.helper> data(IContext context, myfirstmodule.proxies.Entity _entity)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Entity", _entity == null ? null : _entity.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "MyFirstModule.Data", params);
			java.util.List<myfirstmodule.proxies.helper> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<myfirstmodule.proxies.helper>();
				for (IMendixObject obj : objs)
					result.add(myfirstmodule.proxies.helper.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static myfirstmodule.proxies.Entity microflow(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MyFirstModule.Microflow", params);
			return result == null ? null : myfirstmodule.proxies.Entity.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void microflow_2(IContext context, myfirstmodule.proxies.Entity _entity)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Entity", _entity == null ? null : _entity.getMendixObject());
			Core.execute(context, "MyFirstModule.Microflow_2", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<myfirstmodule.proxies.helper> retrieveData(IContext context, myfirstmodule.proxies.Entity _entity)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Entity", _entity == null ? null : _entity.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "MyFirstModule.RetrieveData", params);
			java.util.List<myfirstmodule.proxies.helper> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<myfirstmodule.proxies.helper>();
				for (IMendixObject obj : objs)
					result.add(myfirstmodule.proxies.helper.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}